// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inline_object_partial.proto

package io.beckn.proto;

public final class InlineObjectPartialProtos {
  private InlineObjectPartialProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_beckn_proto_InlineObjectPartial_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_beckn_proto_InlineObjectPartial_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_beckn_proto_InlineObjectPartial_Context_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_beckn_proto_InlineObjectPartial_Context_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033inline_object_partial.proto\022\013beckn_pro" +
      "to\"\333\005\n\023InlineObjectPartial\0229\n\007context\030\001 " +
      "\001(\0132(.beckn_proto.InlineObjectPartial.Co" +
      "ntext\032\210\005\n\007Context\022\016\n\006domain\030\001 \001(\t\022\017\n\007cou" +
      "ntry\030\002 \001(\t\022\014\n\004city\030\003 \001(\t\022C\n\006action\030\004 \001(\016" +
      "23.beckn_proto.InlineObjectPartial.Conte" +
      "xt.ActionEnum\022\035\n\025coreUnderscoreversion\030\005" +
      " \001(\t\022\027\n\017bapUnderscoreid\030\006 \001(\t\022\030\n\020bapUnde" +
      "rscoreuri\030\007 \001(\t\022\027\n\017bppUnderscoreid\030\010 \001(\t" +
      "\022\030\n\020bppUnderscoreuri\030\t \001(\t\022\037\n\027transactio",
      "nUnderscoreid\030\n \001(\t\022\033\n\023messageUnderscore" +
      "id\030\013 \001(\t\022\021\n\ttimestamp\030\014 \001(\t\022\013\n\003key\030\r \001(\t" +
      "\022\013\n\003ttl\030\016 \001(\t\"\230\002\n\nActionEnum\022\n\n\006SEARCH\020\000" +
      "\022\n\n\006SELECT\020\001\022\010\n\004INIT\020\002\022\013\n\007CONFIRM\020\003\022\n\n\006U" +
      "PDATE\020\004\022\n\n\006STATUS\020\005\022\t\n\005TRACK\020\006\022\n\n\006CANCEL" +
      "\020\007\022\n\n\006RATING\020\010\022\013\n\007SUPPORT\020\t\022\r\n\tON_SEARCH" +
      "\020\n\022\r\n\tON_SELECT\020\013\022\013\n\007ON_INIT\020\014\022\016\n\nON_CON" +
      "FIRM\020\r\022\r\n\tON_UPDATE\020\016\022\r\n\tON_STATUS\020\017\022\014\n\010" +
      "ON_TRACK\020\020\022\r\n\tON_CANCEL\020\021\022\r\n\tON_RATING\020\022" +
      "\022\016\n\nON_SUPPORT\020\023B-\n\016io.beckn.protoB\031Inli",
      "neObjectPartialProtosP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_beckn_proto_InlineObjectPartial_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_beckn_proto_InlineObjectPartial_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_beckn_proto_InlineObjectPartial_descriptor,
        new java.lang.String[] { "Context", });
    internal_static_beckn_proto_InlineObjectPartial_Context_descriptor =
      internal_static_beckn_proto_InlineObjectPartial_descriptor.getNestedTypes().get(0);
    internal_static_beckn_proto_InlineObjectPartial_Context_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_beckn_proto_InlineObjectPartial_Context_descriptor,
        new java.lang.String[] { "Domain", "Country", "City", "Action", "CoreUnderscoreversion", "BapUnderscoreid", "BapUnderscoreuri", "BppUnderscoreid", "BppUnderscoreuri", "TransactionUnderscoreid", "MessageUnderscoreid", "Timestamp", "Key", "Ttl", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
