// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inline_object.proto

package io.beckn.proto;

public final class InlineObjectProtos {
  private InlineObjectProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_beckn_proto_InlineObject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_beckn_proto_InlineObject_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_beckn_proto_InlineObject_Context_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_beckn_proto_InlineObject_Context_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_beckn_proto_InlineObject_SearchMessage_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_beckn_proto_InlineObject_SearchMessage_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_beckn_proto_InlineObject_SearchMessage_Intent_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_beckn_proto_InlineObject_SearchMessage_Intent_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_beckn_proto_InlineObject_SearchMessage_Intent_Provider_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_beckn_proto_InlineObject_SearchMessage_Intent_Provider_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_beckn_proto_InlineObject_SearchMessage_Intent_DescriptorObj_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_beckn_proto_InlineObject_SearchMessage_Intent_DescriptorObj_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023inline_object.proto\022\013beckn_proto\"\306\t\n\014I" +
      "nlineObject\0222\n\007context\030\001 \001(\0132!.beckn_pro" +
      "to.InlineObject.Context\0228\n\007message\030\002 \001(\013" +
      "2\'.beckn_proto.InlineObject.SearchMessag" +
      "e\032\201\005\n\007Context\022\016\n\006domain\030\001 \001(\t\022\017\n\007country" +
      "\030\002 \001(\t\022\014\n\004city\030\003 \001(\t\022<\n\006action\030\004 \001(\0162,.b" +
      "eckn_proto.InlineObject.Context.ActionEn" +
      "um\022\035\n\025coreUnderscoreversion\030\005 \001(\t\022\027\n\017bap" +
      "Underscoreid\030\006 \001(\t\022\030\n\020bapUnderscoreuri\030\007" +
      " \001(\t\022\027\n\017bppUnderscoreid\030\010 \001(\t\022\030\n\020bppUnde",
      "rscoreuri\030\t \001(\t\022\037\n\027transactionUnderscore" +
      "id\030\n \001(\t\022\033\n\023messageUnderscoreid\030\013 \001(\t\022\021\n" +
      "\ttimestamp\030\014 \001(\t\022\013\n\003key\030\r \001(\t\022\013\n\003ttl\030\016 \001" +
      "(\t\"\230\002\n\nActionEnum\022\n\n\006SEARCH\020\000\022\n\n\006SELECT\020" +
      "\001\022\010\n\004INIT\020\002\022\013\n\007CONFIRM\020\003\022\n\n\006UPDATE\020\004\022\n\n\006" +
      "STATUS\020\005\022\t\n\005TRACK\020\006\022\n\n\006CANCEL\020\007\022\n\n\006RATIN" +
      "G\020\010\022\013\n\007SUPPORT\020\t\022\r\n\tON_SEARCH\020\n\022\r\n\tON_SE" +
      "LECT\020\013\022\013\n\007ON_INIT\020\014\022\016\n\nON_CONFIRM\020\r\022\r\n\tO" +
      "N_UPDATE\020\016\022\r\n\tON_STATUS\020\017\022\014\n\010ON_TRACK\020\020\022" +
      "\r\n\tON_CANCEL\020\021\022\r\n\tON_RATING\020\022\022\016\n\nON_SUPP",
      "ORT\020\023\032\303\003\n\rSearchMessage\022>\n\006intent\030\001 \001(\0132" +
      "..beckn_proto.InlineObject.SearchMessage" +
      ".Intent\032\361\002\n\006Intent\022S\n\rdescriptorObj\030\001 \001(" +
      "\0132<.beckn_proto.InlineObject.SearchMessa" +
      "ge.Intent.DescriptorObj\022I\n\010provider\030\002 \001(" +
      "\01327.beckn_proto.InlineObject.SearchMessa" +
      "ge.Intent.Provider\032\026\n\010Provider\022\n\n\002id\030\001 \001" +
      "(\t\032\256\001\n\rDescriptorObj\022\014\n\004name\030\001 \001(\t\022\014\n\004co" +
      "de\030\002 \001(\t\022\016\n\006symbol\030\003 \001(\t\022\033\n\023shortUndersc" +
      "oredesc\030\004 \001(\t\022\032\n\022longUnderscoredesc\030\005 \001(",
      "\t\022\016\n\006images\030\006 \003(\t\022\r\n\005audio\030\007 \001(\t\022\031\n\021dUnd" +
      "erscorerender\030\010 \001(\tB&\n\016io.beckn.protoB\022I" +
      "nlineObjectProtosP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_beckn_proto_InlineObject_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_beckn_proto_InlineObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_beckn_proto_InlineObject_descriptor,
        new java.lang.String[] { "Context", "Message", });
    internal_static_beckn_proto_InlineObject_Context_descriptor =
      internal_static_beckn_proto_InlineObject_descriptor.getNestedTypes().get(0);
    internal_static_beckn_proto_InlineObject_Context_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_beckn_proto_InlineObject_Context_descriptor,
        new java.lang.String[] { "Domain", "Country", "City", "Action", "CoreUnderscoreversion", "BapUnderscoreid", "BapUnderscoreuri", "BppUnderscoreid", "BppUnderscoreuri", "TransactionUnderscoreid", "MessageUnderscoreid", "Timestamp", "Key", "Ttl", });
    internal_static_beckn_proto_InlineObject_SearchMessage_descriptor =
      internal_static_beckn_proto_InlineObject_descriptor.getNestedTypes().get(1);
    internal_static_beckn_proto_InlineObject_SearchMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_beckn_proto_InlineObject_SearchMessage_descriptor,
        new java.lang.String[] { "Intent", });
    internal_static_beckn_proto_InlineObject_SearchMessage_Intent_descriptor =
      internal_static_beckn_proto_InlineObject_SearchMessage_descriptor.getNestedTypes().get(0);
    internal_static_beckn_proto_InlineObject_SearchMessage_Intent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_beckn_proto_InlineObject_SearchMessage_Intent_descriptor,
        new java.lang.String[] { "DescriptorObj", "Provider", });
    internal_static_beckn_proto_InlineObject_SearchMessage_Intent_Provider_descriptor =
      internal_static_beckn_proto_InlineObject_SearchMessage_Intent_descriptor.getNestedTypes().get(0);
    internal_static_beckn_proto_InlineObject_SearchMessage_Intent_Provider_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_beckn_proto_InlineObject_SearchMessage_Intent_Provider_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_beckn_proto_InlineObject_SearchMessage_Intent_DescriptorObj_descriptor =
      internal_static_beckn_proto_InlineObject_SearchMessage_Intent_descriptor.getNestedTypes().get(1);
    internal_static_beckn_proto_InlineObject_SearchMessage_Intent_DescriptorObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_beckn_proto_InlineObject_SearchMessage_Intent_DescriptorObj_descriptor,
        new java.lang.String[] { "Name", "Code", "Symbol", "ShortUnderscoredesc", "LongUnderscoredesc", "Images", "Audio", "DUnderscorerender", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
