// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inline_object.proto

package io.beckn.proto;

public interface InlineObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:beckn_proto.InlineObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .beckn_proto.InlineObject.Context context = 1;</code>
   */
  boolean hasContext();
  /**
   * <code>optional .beckn_proto.InlineObject.Context context = 1;</code>
   */
  io.beckn.proto.InlineObject.Context getContext();
  /**
   * <code>optional .beckn_proto.InlineObject.Context context = 1;</code>
   */
  io.beckn.proto.InlineObject.ContextOrBuilder getContextOrBuilder();

  /**
   * <code>optional .beckn_proto.InlineObject.SearchMessage message = 2;</code>
   */
  boolean hasMessage();
  /**
   * <code>optional .beckn_proto.InlineObject.SearchMessage message = 2;</code>
   */
  io.beckn.proto.InlineObject.SearchMessage getMessage();
  /**
   * <code>optional .beckn_proto.InlineObject.SearchMessage message = 2;</code>
   */
  io.beckn.proto.InlineObject.SearchMessageOrBuilder getMessageOrBuilder();
}
