// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inline_object_partial.proto

package io.beckn.proto;

public interface InlineObjectPartialOrBuilder extends
    // @@protoc_insertion_point(interface_extends:beckn_proto.InlineObjectPartial)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .beckn_proto.InlineObjectPartial.Context context = 1;</code>
   */
  boolean hasContext();
  /**
   * <code>optional .beckn_proto.InlineObjectPartial.Context context = 1;</code>
   */
  io.beckn.proto.InlineObjectPartial.Context getContext();
  /**
   * <code>optional .beckn_proto.InlineObjectPartial.Context context = 1;</code>
   */
  io.beckn.proto.InlineObjectPartial.ContextOrBuilder getContextOrBuilder();
}
