/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package innovation.hackathon.jan22;

import org.junit.Test;

import static org.junit.Assert.assertTrue;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        assertTrue(true);
    }
}
